# Generated by Django 3.2.24 on 2024-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SIN', 'Single'), ('DUO', 'Double'), ('TRI', 'Triple'), ('DLX', 'Deluxe'), ('SUT', 'Suite'), ('QUN', 'Queen'), ('KNG', 'king'), ('VLA', 'Villa')], default='SIN', max_length=3)),
                ('room_no', models.IntegerField()),
            ],
        ),
    ]
