# Generated by Django 3.2.24 on 2024-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceans_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['room_no']},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.IntegerField(unique=True),
        ),
    ]
