# Generated by Django 3.2.24 on 2024-06-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceans_hotel', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
