# Generated by Django 3.2.24 on 2024-06-30 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oceans_hotel', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('SIN', 'Single'), ('DUO', 'Double'), ('TRI', 'Triple'), ('DLX', 'Deluxe'), ('SUT', 'Suite')], default='SIN', max_length=3),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('room_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='oceans_hotel.rooms')),
            ],
            options={
                'ordering': ['room_booked'],
            },
        ),
    ]
