# Generated by Django 3.2.24 on 2024-07-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceans_hotel', '0005_auto_20240630_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-check_in']},
        ),
    ]
