# Generated by Django 3.2.24 on 2024-07-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceans_hotel', '0006_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['check_in']},
        ),
    ]
