# Generated by Django 3.2.24 on 2024-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceans_hotel', '0007_alter_bookings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
